# This workflow update the sun position figures, daily

name: update

on:
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00” UTC
  push:
    branches: [ main ]
  workflow_dispatch: # allows to trigger a workflow run manually

jobs:
  compute-and-report:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: 'main'
        fetch-depth: 0 # Fetch all history for all branches and tags.

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        channel-priority: strict
        mamba-version: "*"
        activate-environment: brest-sun
        auto-update-conda: false
        python-version: 3.8

    - name: Set up conda environment
      run: |
        mamba env update -f environment.yml

    - shell: bash -l {0}
      run: |
        conda info
        conda list
        export LC_ALL="en_US.UTF-8"
        export LC_CTYPE="en_US.UTF-8"
        sudo dpkg-reconfigure locales

    - name: Update figures
      shell: bash -l {0}
      run: |
        python Position-soleil-static.py
        ls -l

    - name: Save figures online
      uses: EndBug/add-and-commit@v4.4.0
      with:
        author_name: gmaze-bot
        author_email: gmaze@ifremer.fr
        message: "Update figures"
        add: "*.json --force"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
